### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by adamjri** [ShootMe/LiveSplit.HollowKnight#22]
Livesplit split properly and then immediately split again without prompting. Tried to undo split but the timer stopped and would not restart when trying to pause or unpause. Autosplitter settings were correct. Error logs show thousands of index out of range errors during the time I tried to undo split and restart timer. They do not seem to be prompted by me pressing buttons, rather, they repeat regularly many times a second over the course of about a minute. When I attempt to close livesplit it throws a different error. I provide a screenshot of the 2 error xmls here. https://imgur.com/a/fzEr5Md

**Comment by ShootMe** [comment]
I don't know how it is causing that to happen. There are numerous bounds checking in the HandleSplits method. If you can reproduce this I can try and look into it more, would need to know the steps and most likely have access to your splits. As it stands I don't really have any way to know what is going on.
