### ISSUE TITLE
Make the “core logic” compile on linux

### ISSUE THREAD

**Issue by lukasjuhrich** [ShootMe/LiveSplit.HollowKnight#34]
Hi,

This is a long shot. tl;dr: I want a working HK autosplitter on linux to use with [LiveSplitOne](https://github.com/LiveSplit/LiveSplitOne).

Would it be somehow possible to decouple the “core logic”, i.e. the memory introspection, from the UI and other parts that depend on the [LiveSplit](https://github.com/LiveSplit/LiveSplit) project?

The main motivation is that Livesplit, and dependent components such as [LiveSplit.Server](https://github.com/LiveSplit/LiveSplit.Server), is incompatible with linux, and I would guess that there are no 
However, there is LiveSplitOne which has an API one can talk to.

My idea would be to build a custom „livesplit server“ that communicates events via websockets to LiveSplitOne and uses code from this autosplitter to provide that functionality.

Please bear with me as I don't fully understand the whole livesplit ecosystem yet; this is partly because I don't have access to a windows PC and cannot compile / try out how these things are supposed to work.

One could provide this „separate view“ in a different solution.

**Comment by cerpintext** [comment]
If the memory logic from the game between the OSes is similar than maybe, that's the main issue from what I've gathered in the past

**Comment by ShadiestGoat** [comment]
Heya, according to https://github.com/R3FR4G/Livesplit-Server-Autosplitter the problem could be the `process.MainModule.BaseAdress`

**Comment by lukasjuhrich** [comment]
Given that the livesplit project this plugin bbuilds on is considered legacy, I think it's wise to close this issue and to instead redirect any enthusiasm towards LiveSplit/LiveSplit#2037 and LiveSplit/livesplit-core#176

**Comment by Ordoviz** [comment]
I wrote a standalone autosplitter for Linux, see https://github.com/Ordoviz/hkautosplit
