### ISSUE TITLE
Index out of range exception after updating autospliter to newest version

### ISSUE THREAD

**Issue by LMH01** [ShootMe/LiveSplit.HollowKnight#41]
**How it happened**
I was not using livesplit for some time so when i opened it up yesterday i got the information that a new update is available (A new update for livesplit and a new update for this autosplitter). With the livesplit update it was not possible to let it update itself so i updated livesplit manually. After i updated livesplit and loaded the splits with the autosplitter it worked properly. I did not update the autosplitter for Hollow Knight manually though. When i launched livesplit today i got reminded of the update for the autosplitter and used the autoupdate feature to update it. That was when my problems started.

**The problem**
After i updated the autosplitter to the latest version, i can no longer access the settings and add new splits. Everytime i click on the button Settings the program crashes with this error:

`************** Ausnahmetext **************
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei LiveSplit.HollowKnight.HollowKnightSettings.GetAvailableSplits()
   bei LiveSplit.HollowKnight.HollowKnightSettings.LoadSettings()
   bei System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Steps to reproduce**
1. Open live split
2. Click Edit splits
3. Click Settings
4. Program shows error message

**Tried fixes:**
1. Download livesplit again -> Same error, except that the autosplitter for Hollow Knight has to be activated again
2. Create blank split -> For that i just closed the current split and clicked edit split. After choosing Hollow Knight, activating the auto splitter and clicking on settings, the same error message appears
3. Download a split from speedrun.com and use the autosplitter that way -> After the speedrun split has been download and the settings button are clicked the same error occurs

I have attached the layout and split profiles.
If you can't fix this issue is there any possible way on how i can downpatch to the last version, because that worked properly.

[Livesplit files.zip](https://github.com/ShootMe/LiveSplit.HollowKnight/files/6604562/Livesplit.files.zip)

**Comment by cerpintext** [comment]
fixed that fatfinger in #42. sorry
