### ISSUE TITLE
Update to HK v1.5 with Unity2020

### ISSUE THREAD

**Issue by cerpintext** [ShootMe/LiveSplit.HollowKnight#43]
Just attempting to connect the current autosplitter to the newest update of HK results in this error being thrown and caught in the windows event viewer:

```
Object reference not set to an instance of an object.

   at LiveSplit.HollowKnight.HollowKnightMemory.AcceptingInput()
   at LiveSplit.HollowKnight.HollowKnightComponent.LogValues()
   at LiveSplit.View.TimerForm.<TimerElapsed>b__185_0()
```
So it seems the underlying memory readers has to be customised to handle Unity2020.

To make things extra fun this is what happens when trying to search in CheatEngine 7.2 manually. pain (and also makes me afraid there's more to do than "just" handling the 64bit Unity2020??) :)
![image](https://user-images.githubusercontent.com/27957371/121036693-28a46a00-c7af-11eb-8248-c7bb52514da7.png)

**Comment by cerpintext** [comment]
official unity version numbers from UnityPlayer.dll just to have them stored and available:
```
file ver:     2020.2.2.33144
prod ver:  2020.2.2.426360

```

![image](https://user-images.githubusercontent.com/27957371/121039747-a7020b80-c7b1-11eb-8cc6-12e2fd34ca4f.png)

**Comment by slaurent22** [comment]
This should be closed, I think

**Comment by cerpintext** [comment]
true. thanks for reminder
