### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by vision976899957** [ShootMe/LiveSplit.HollowKnight#7]
Thank you
With the help of your documentation, I have done this.
http://fearlessrevolution.com/viewtopic.php?f=4&t=7739
thank you very much

But I am still very curious, how did you know this?

**Comment by ShootMe** [comment]
It's not a simple process to explain. But using dnSpy to decompile the code and Cheat Engine to get offsets is the basic explanation. If you need more you can find me on the HK discord.

**Comment by vision976899957** [comment]
Thank yo.I am very curious about this, so I will find you soon. We will meet again soon.So you can speak Chinese?!
